### ISSUE TITLE
Add support for Python3

### ISSUE THREAD

**Issue by yanickrochon** [bitdotioinc/pgsqlite#8]
```
$ pip install pysqlite
Collecting pysqlite
  Downloading pysqlite-2.8.3.tar.gz (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 kB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

As Python 3 was released in 2008, and as mentioned in this [StackOverflow answer dating back in 2014](https://stackoverflow.com/questions/23181197/install-pysqlite-in-virtualenv-with-python3-support), with Python 2 being [sunsetted on January 2020](https://www.python.org/doc/sunset-python-2/), will this package be updated to finally be compatible with Python 3?

Thanks!

**Comment by adamf** [comment]
Hi! I think you opened this bug on the wrong package - this package is _PG_sqlite, not _PY_sqlite. This package only supports Python 3 (we've never even tested on Python 2)
