### ISSUE TITLE
Programmatic access via cURL returns 502 Server Error

### ISSUE THREAD

**Issue by silvioprog** [bitdotioinc/pgsqlite#9]
Hi.

I have been trying to access the [bit.io](https://bit.io) service using cURL as suggested by [its documentation](https://docs.bit.io/docs/examples-different-ways-to-connect#create-a-repo) (please replace `MY_BITIO_KEY` by your key):

```bash
% curl --request POST \
     --url https://api.bit.io/api/v1beta/repos/ \
     --header 'Accept: application/json' \
     --header 'Content-Type: application/json' \
     --header 'Authorization: Bearer <MY_BITIO_KEY>' \
     --data '
{
     "name": "my_new_repo",
     "description": My new repo."
}
'
```
but receiving the following error:

```html
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

is there anything I'm doing wrong? 😕

TIA for any help!

**Comment by jmo-qap** [comment]
That documentation page is for the v1 bit.io API and has been deprecated. https://docs.bit.io/docs/connecting-via-the-api and https://docs.bit.io/reference/ are up-to-date. If you have issues with the bit.io API, support@bit.io or https://docs.bit.io/discuss are the best way to get a response. This repo is for our SQLite converter.
